import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import supabase from '@/utils/supabase'
import { GetStaticProps } from 'next'

interface ExamProps {
    video: {id: string; title: string; tag: string; video_url: string}[];
}

export default function Home({ video }: ExamProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1>Videos for<br/>EAPA2101</h1>
        <div className={styles.grid}>
          {video.map((video: {
                id: string;
                title: string; 
                video_url: string;}) => (
                <div className={styles.card} key={video.id}>{video.title}</div>
            ))}
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { data: video } = await supabase.from("video").select().or('tag.cs.{EAPA2101}');
  
  return {
      props: {
        video,
      },
  };
};