import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import supabase from '@/utils/supabase'
import { GetStaticProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

interface ExamProps {
  exam: {id: string; title: string; description: string; video_url: string}[];
}

export default function Home({ exam }: ExamProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1>Prepare for<br/>GIS exam</h1>
        <div className={styles.grid}>
          {exam.map((exam: {
                id: string;
                title: string; 
                video_url: string;}) => (
                <div className={styles.card} key={exam.id}>{exam.title}</div>
            ))}
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const { data: exam } = await supabase.from("exam").select("*")
  
  return {
      props: {
        exam,
      },
  };
};